### PR TITLE
Filter: Fix state sync issue

### LINKED ISSUE #62: Visual query builder: Removed group by or aggregation is automatically brought back when filter is removed
Noticed that when removing a filter from a query. The previously removed group by and aggregation appeared back after the filter was removed:

https://user-images.githubusercontent.com/2376619/160645235-f81b12fa-868d-446b-8b93-d4aa071ad6de.mov

### PR DESCRIPTION
**Pull request by zoltanbedi**
Because of the debounceing changes in the query props was not in sync with the Filter component.

Fixes #62

### CODE REVIEW

File: src/components/visual-query-builder/BQWhereRow.tsx [hunk 1]
```diff
@@ -41,6 +41,11 @@ export function BQWhereRow({ query, apiClient, onQueryChange }: BQWhereRowProps)
     [sql]
   );
 
+  // Need to keep the state in sync with the props
+  useDeepCompareEffect(() => {
+    setSql(query.sql);
+  }, [query.sql]);
+
   return (
```
Comment (dprokop) [inline src/components/visual-query-builder/BQWhereRow.tsx:49]: Let's skip the debounced query at all, since we have the run query button now.

Comment (zoltanbedi) [reply src/components/visual-query-builder/BQWhereRow.tsx]: I've removed the debounce now and it works as expected.

**Review by dprokop — APPROVED** [review]
Awesome, now it works as expected and the code is so much simpler!
