### PR TITLE
Fix: backward compatibility issue

### LINKED ISSUE #121: Not possible to create datasource using Grafana 8.2.7
Attempting to create a database results in the error:
`Object(...) is not a function Evaluating https://<<REMOVED>>>/public/plugins/grafana-bigquery-datasource/module.js Loading plugins/grafana-bigquery-datasource/module`

Grafana:  8.2.7
Plugin: grafana-bigquery-datasource @ 1.1.0

### PR DESCRIPTION
**Pull request by zoltanbedi**
I tested this with this docker command.

```
  docker run -d \
    -e GF_DEFAULT_APP_MODE=development \
    -e GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-bigquery-datasource \
    -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin \
    -e GF_AUTH_ANONYMOUS_ENABLED=true \
    -e GF_AUTH_BASIC_ENABLED=false \
    -p 3001:3000 \
    -v ~/GitHub/grafana/plugins/google-bigquery-datasource:/var/lib/grafana/plugins/google-bigquery-datasource \
    grafana/grafana:8.0.0
```

Fixes #121

### CODE REVIEW

File: src/components/QueryHeader.tsx [hunk 1]
```diff
@@ -106,24 +107,53 @@ export function QueryHeader({
...
+          fallBackComponent={
+            <InlineField label="Processing location" labelWidth={20}>
+              <Select
+                placeholder="Select location"
+                allowCustomValue
+                value={location}
+                onChange={({ value }) => value && onChange({ ...query, location: value || DEFAULT_REGION })}
+                options={PROCESSING_LOCATIONS}
+              />
+            </InlineField>
```
Comment (dprokop) [inline src/components/QueryHeader.tsx:121]: this one actually doesn't look that bad in the UI!

File: src/components/QueryHeader.tsx [hunk 2]
```diff
@@ -9,6 +9,7 @@ import { DEFAULT_REGION, PROCESSING_LOCATIONS, QUERY_FORMAT_OPTIONS } from '../c
 import { BigQueryQueryNG, QueryFormat, QueryRowFilter, QueryWithDefaults } from '../types';
 import { ConfirmModal } from './ConfirmModal';
 import { DatasetSelector } from './DatasetSelector';
+import { ErrorBoundary } from './ErrorBoundary';
```
Comment (dprokop) [inline src/components/QueryHeader.tsx:12]: Isn't this exposed from grafana-ui?

**Review by dprokop — APPROVED** [review]
LGTM, one comment about ErrorBoundary.
